### ISSUE TITLE
Does this require to patch the Linino?

### ISSUE THREAD

**Issue by murmlgrmpf** [firmata/StandardFirmataYun#1]
Hi,

does using this need the Linino part of the yun to be patched in order to avoid inference with the bridge?

See:
http://forum.arduino.cc/index.php?topic=191820.0

Best,
Thomas

**Comment by murmlgrmpf** [comment]
Sorry, stupid question, it is using i2c instead of the serial.

**Comment by soundanalogous** [comment]
It's not a stupid question. In the past I had to make a modification in the Linino part (step 6 [here](https://github.com/soundanalogous/yunBreakout/blob/master/README.md)), but I believe this code makes it so that is no longer necessary: https://github.com/firmata/StandardFirmataYun/blob/master/StandardFirmataYun.ino#L727-L733

I haven't tested it myself as the code referenced above was contributed. I'll try to find time to verify later this weekend. It's possible it may work with some Firmata client libraries but not with others depending on how the client handles the startup sequence.

**Comment by murmlgrmpf** [comment]
Thanks for the quick response!
Right after closing the issue, I noticed that it is using Serial1 for the firmata uplink..
My plan is to use pymata-aio on the linino side, so I will probably find out tomorrow whether this client works without patching.

btw: nice video ;-)

**Comment by soundanalogous** [comment]
I think pymata-aio will work work since it is by the same author (@MrYsLab) who contributed the patch for StandardFirmataYun. I'm just not sure about other Firmata client libraries.

**Comment by soundanalogous** [comment]
LOL I didn't realize I pasted the wrong link. How embarrassing! Updated with correct link.

**Comment by MrYsLab** [comment]
The original [PMata](https://github.com/MrYsLab/PyMata) will work with the Yun since it is Python 2.7 compatible. Sadly, [ pymata-aio](https://github.com/MrYsLab/pymata-aio) could not be tested because linino does not  easily support Python 3.5. If you want to try it and can figure out how to get Python 3.5 on linino, please let me know how you were able to get 3.5 on linino.

**Comment by murmlgrmpf** [comment]
Thanks for the hint! I didn't get to test it yet but i will report as soon as possible.

**Comment by murmlgrmpf** [comment]
I have just got the pymata blink example working, but I needed to disable the console in inittab. Otherwise pymata would fail in either of two ways:

```
root@Arduino:/mnt/sda1/PyMata-master/examples# python pymata_blink.py

Python Version 2.7.3 (default, Nov 13 2014, 21:40:08) 
[GCC 4.6.3 20120201 (prerelease)]

PyMata version 2.11  Copyright(C) 2013-15 Alan Yorinks    All rights reserved.

Opening Arduino Serial port /dev/ttyATH0 

Please wait while Arduino is being detected. This can take up to 30 seconds ...
Traceback (most recent call last):
  File "pymata_blink.py", line 34, in <module>
    board = PyMata("/dev/ttyATH0", verbose=True)
  File "/usr/lib/python2.7/site-packages/PyMata/pymata.py", line 196, in __init__
    if not self._command_handler.auto_discover_board(self.verbose):
  File "/usr/lib/python2.7/site-packages/PyMata/pymata_command_handler.py", line 238, in auto_discover_board
    self.send_sysex(self.ANALOG_MAPPING_QUERY, None)
  File "/usr/lib/python2.7/site-packages/PyMata/pymata_command_handler.py", line 619, in send_sysex
    self.pymata.transport.write(data)
  File "/usr/lib/python2.7/site-packages/PyMata/pymata_serial.py", line 107, in write
    self.arduino.write(data)
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 490, in write
    if not self._isOpen: raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
  File "/usr/lib/python2.7/site-packages/PyMata/pymata_command_handler.py", line 757, in run
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

Or

```
root@Arduino:/mnt/sda1/PyMata-master/examples# python pymata_blink.py

Python Version 2.7.3 (default, Nov 13 2014, 21:40:08) 
[GCC 4.6.3 20120201 (prerelease)]

PyMata version 2.11  Copyright(C) 2013-15 Alan Yorinks    All rights reserved.

Opening Arduino Serial port /dev/ttyATH0 

Please wait while Arduino is being detected. This can take up to 30 seconds ...
Traceback (most recent call last):
  File "pymata_blink.py", line 34, in <module>
    board = PyMata("/dev/ttyATH0", verbose=True)
  File "/usr/lib/python2.7/site-packages/PyMata/pymata.py", line 196, in __init__
    if not self._command_handler.auto_discover_board(self.verbose):
  File "/usr/lib/python2.7/site-packages/PyMata/pymata_command_handler.py", line 238, in auto_discover_board
    self.send_sysex(self.ANALOG_MAPPING_QUERY, None)
  File "/usr/lib/python2.7/site-packages/PyMata/pymata_command_handler.py", line 619, in send_sysex
    self.pymata.transport.write(data)
  File "/usr/lib/python2.7/site-packages/PyMata/pymata_serial.py", line 107, in write
    self.arduino.write(data)
  File "/usr/lib/python2.7/site-packages/serial/serialposix.py", line 490, in write
    if not self._isOpen: raise portNotOpenError
serial.serialutil.SerialException: Attempting to use a port that is not open
```

**Comment by MrYsLab** [comment]
It has been a very long while since I played with the Yun, so my memory may be faulty. But I think if you use this sketch you do not have to disable the console in inittab: https://github.com/MrYsLab/s2a_fm/tree/master/Snap!Files/Snap!Mobile/StandardFirmataYun/StandardFirmataYun

I developed this sketch for this article:
http://www.instructables.com/id/The-SnapMobile-Start-Your-Physical-Computing-Engin/?ALLSTEPS

**Comment by murmlgrmpf** [comment]
@soundanalogous thought, that he had implemented the fix that you suggested (delaying and reading until there are no messages on the console for 1000ms), but he could not test it. I have tested it now, and it is failing on me.

**Comment by MrYsLab** [comment]
@murmlgrmpf  If it does work with disabling the console, it appears then that is the only solution. I am not sure if something changed over time with Linino revisions or not.

**Comment by murmlgrmpf** [comment]
I guess so too, disabling the console is the savest method to get firmata working on the yun, I just wanted to document this here such that others know about it when they read this thread.
